### PR TITLE
Update theme for October and reword

### PR DESCRIPTION
**Pull request by cristeahub**
This pr adds a new theme that I think will go great with October: Scary Movies.

I also reworded the header on the main page that says the current theme to reflect that it spans longer than a month at a time.

When opening your Pull Request, we encourage you to do the following (you can add an X to check each task):

- [x] Run `make lint` to ensure that all the files are formatted and using best practices.
- [x] Link to any issues this PR is solving.

### CODE REVIEW

**Comment by sigvef** [comment]
lgtm!

**Comment by sigvef** [comment]
@lionleaf

**Comment by lionleaf** [comment]
In the mountains. Will deploy when I'm on a laptop again tomorrow or Monday :)

**Comment by lionleaf** [comment]
Deployed

**Pull request merged**
