### PR TITLE
Hide new dweet box

### LINKED ISSUE #3: Hide preview canvas when not writing a dweet

### PR DESCRIPTION
**Pull request by stianjensen**
This hides the UI for creating a new dweet by default, so the first you see when entering the page is now instead the top dweet. To show the UI, you must click the 'create a new dweet' button at the top of the feed.

The UI for creating dweet is also cleaned up a little, to look more similar to dweet editing and remove visual noise.

This fixes #3.

screenshot 2017-03-12 18 36 26

screenshot 2017-03-12 18 36 33

### CODE REVIEW

**Comment by stianjensen** [comment]
I changed the color of the create-button, hid it when you click it, and added a slide-down animation.

**Comment by lionleaf** [comment]
Looks good 👍 Any more input @aleksanb? If not I'll deploy it

screenshot 2017-03-12 19 33 15

**Comment by stianjensen** [comment]
I'll try another iteration on designing the button to look more 'clickable'

**Comment by aleksanb** [comment]
Don't merge yet @lionleaf still usability issues which can be improved.

**Comment by aleksanb** [comment]
With the new dweet-styling: 
image

When i fake being a new user, i don't understand that i can click on the black textedit thing and write things there, the old style was better in that regard.
image

There's no doubt that you can edit this one (due to the horrible textbox border)

**Comment by lionleaf** [comment]
I agree @aleksanb . The same goes for other people's dweets, it is not obvious that they are editable. Blinking cursor? Make it look more like a text field somehow?

Also, change the "Dweet!" button to say "Post dweet"?

**Comment by stianjensen** [comment]
I reworded and added a plus icon to the create button:
screenshot 2017-03-12 20 01 46

**Comment by stianjensen** [comment]
The edit field now auto-focuses, and I increased the font size to all the monospaced fonts now align vertically.
screenshot 2017-03-12 20 00 58

**Comment by lionleaf** [comment]
Lower-case "Dweet" in "Post Dweet!". 

Flight is taking off soon, so I'll deploy once I'm in London 👍

**Comment by stianjensen** [comment]
> Lower-case "Dweet" in "Post Dweet!".

ping

**Pull request merged**
