### PR TITLE
Redesign and cleanup header

### PR DESCRIPTION
**Pull request by stianjensen**
This reduces the height of the header by 50px, making the content of the
page more prominent.
It also reduces the font size of the dropdown menu so every item in it
can fit on one line.

screenshot 2017-03-12 18 53 41

### CODE REVIEW

**Comment by stianjensen** [comment]
> Let's max-width the header, so it doesn't get all out of whack on larger screens.

Done

**Comment by lionleaf** [comment]
Seems to break the drop-down menu when I tried it:

screenshot 2017-03-12 19 19 28

**Comment by stianjensen** [comment]
> Seems to break the drop-down menu when I tried it:

Yup, just caught that myself (it was due to the max-widh). Should work again now

**Comment by lionleaf** [comment]
Nice!

Still some dropdown issues:
screenshot 2017-03-12 19 24 35

**Comment by stianjensen** [comment]
> Still some dropdown issues:

Lol, of course. Now the fix became a bit more complicated. I'll rethink.

**Comment by stianjensen** [comment]
ping.

Actually, the fix was easy. overflow hidden was not necessary as a clearfix hack, since the height of the header is specified to be 40px anyway.

**Pull request merged**
