### PR TITLE
Add user avatars from gravatar

### PR DESCRIPTION
**Pull request by sigvef**
image

image

image

### CODE REVIEW

**Comment by tbroadley** [comment]
On small screens, the dropdown menu is rendered behind the blank dweet's `iframe`.

image

**Comment by tbroadley** [comment]
Also, when logged out, the "Login or register" links are still styled with a darker background when hovered over:

image

**Comment by tbroadley** [comment]
Rather than displaying the Gravatar logo, maybe the Gravatar image should be hidden when there is none associated with the user's email address.

**Comment by sigvef** [comment]
> On small screens, the dropdown menu is rendered behind the blank dweet's iframe.

Fixed.

> Also, when logged out, the "Login or register" links are still styled with a darker background when hovered over:

Fixed.

> Rather than displaying the Gravatar logo, maybe the Gravatar image should be hidden when there is none associated with the user's email address.

Now the default is Gravatar's auto-generated retro 8-bit images (based off of your email, so different users get different avatars):

image

**Comment by tbroadley** [comment]
Looks sweet! One more comment: On small screens, the current user's name in the top right (which is also a link to the user's profile) is hidden. I think that the Gravatar image should also link to the user's profile, so that it is still possible to access one's profile.

**Pull request merged**
