### PR TITLE
Add special 404 page for dweet subdomain; test dweet views

### PR DESCRIPTION
**Pull request by tbroadley**
This PR closes https://github.com/lionleaf/dwitter/issues/149. It adds a special 404 page for requests to the `dweet` subdomain.

This PR also includes some tests for the `dweet` subdomain's views.

Finally, it fixes some code that the linter had flagged.

image

### CODE REVIEW

**Comment by lionleaf** [comment]
Thanks! Would be awesome to get this working properly.

However the 404 page solution doesn't seem to work. I spent a while trying myself and couldn't get it to work either. I believe you have to change the handler404 in the root urls.py.

It's a bit awkward to test; a useful trick: https://spapas.github.io/2015/04/29/django-show-404-page/ . Or just set debug=false for testing and check dweet.localhost:8000/404

**Comment by tbroadley** [comment]
Thanks @lionleaf, I will give what you suggest a shot!

**Comment by tbroadley** [comment]
Interesting... When I test this locally with `DEBUG = False` and `ALLOWED_HOSTS = ['localhost', 'dweet.localhost']`, I do see the correct 404 page on the `dweet` subdomain.

@lionleaf Did you happen to record the 500 error you received when testing this in production?

`localhost` 404 page:

image

`dweet.localhost` 404 page:

image

**Comment by lionleaf** [comment]
Error in prod by checkout out the PR and going to dweet.dwitter.net/404:


Internal Server Error: /404

NoReverseMatch at /404
Reverse for 'auth_login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Request Method: GET
Request URL: https://dweet.dwitter.net/404
Django Version: 1.9
[...]


That is pretty strange indeed. I can't even get it to work locally :/

**Comment by tbroadley** [comment]
Thanks @lionleaf. This is definitely strange. When I access `dweet.localhost:8000/404`, I seem to get the correct 404 page. I'll keep investigating.

**Comment by lionleaf** [comment]
No idea how or why, but got it to work in prod now 👍

**Comment by tbroadley** [comment]
Awesome!

**Pull request merged**
