### PR TITLE
insert_magic_links filter for dweet and user links

### LINKED ISSUE #244: Magic links for dweet and author mentions
Just like what GitHub does for commit hashes, automatically convert certain patterns to dweet or author links:

* /u/lionleaf -- user link
* /d/123 -- dweet link

### PR DESCRIPTION
**Pull request by atesgoral**
Resolves #244 by introducing a new template filter. This could have been also done as a template tag, but I followed to_gravatar_url (which is a filter inside the templatetags folder) as an example.

Potential improvements:
* [x] Make the regexp more specific to ignore cases where the patterns appear in the middle of a URL etc.

### CODE REVIEW

**Comment by atesgoral** [comment]
I think it the pattern should be either d/n or /d/n, but not both. What do you think? And which pattern do you prefer?

**Comment by lionleaf** [comment]
Nice! I like the use of template tags. Works well locally. Happy to merge and deploy once the linter is happy ^^ 

PS: We've got travis set up to be pretty picky about formatting, so a pro-tip is to run `make lint` locally first :)

**Comment by lionleaf** [comment]
To answer @joeytwiddle :   I want to save #tags for a future hashtag implementation, not for dweet links.

full url compression sounds like a nifty addition though! :D

**Comment by lionleaf** [comment]
fixes #173 and #244 

(that should link the issues properly)

**Comment by stianjensen** [comment]
> fixes #173 and #244 and #150

> (that should link the issues properly)

Heads up, this will only close the first of the three issues 😅

**Comment by lionleaf** [comment]
fixes #244 
fixes #150

**Pull request merged**
