### PR TITLE
add about page stub

### PR DESCRIPTION
**Pull request by lionleaf**
Re-opening of #258 by @whackashoe Thanks for kick-starting this!

Moved to a local branch, so additional commits can be added to the branch `about_page`

Current state:

screen shot 2018-01-17 at 9 21 16 pm
screen shot 2018-01-17 at 9 21 36 pm

Feedback welcome both as responses here and as commits directly to the pull request :D

### CODE REVIEW

**Comment by lionleaf** [comment]
Added some text: 

screen shot 2018-01-17 at 10 39 21 pm

Any thoughts @sigvef ?

**Comment by lionleaf** [comment]
Ugh, forgot to add a few `<a href>` to explain demoparty and link to arkt.is etc. That will have to wait as I'm going to bed. 

Also, should the about page link float right or do something else to look different from the various feeds?

**Comment by sigvef** [comment]
Looks good! Some thoughts:
- You can also add linkify  "contributors" to the contributors tab on GitHub if you want.
- Perhaps we should add a large visible button the the discord chat, or a widget even https://blog.discordapp.com/add-the-discord-widget-to-your-site-d45ffcd718c6
- We could even list a bunch of dwitter-related projects by people in the community!

**Comment by lionleaf** [comment]
New text:
screen shot 2018-01-18 at 9 56 09 pm

**Comment by lionleaf** [comment]
@sigvef I agree with your points on both the discord button and links to community projects. But I'll do them as separate PRs I think.

Thoughts on this version? Made the language a bit more energetic and added links

**Comment by lionleaf** [comment]
screen shot 2018-01-18 at 10 08 38 pm

**Comment by lionleaf** [comment]
fixes #232

**Comment by lionleaf** [comment]
Merging to get something up! Feel free to add more comments and I will fix with new pull requests

**Pull request merged**
