### PR TITLE
User settings

### PR DESCRIPTION
**Pull request by sigvef**

### CODE REVIEW

**Comment by peterhgombos** [comment]
Do we need full names? That's not very demosceney, right?

**Comment by lionleaf** [comment]
Optional full names isn't a problem, but then again there isn't a need. I suggest we just do the email address and the avatar preview/instruction for now. We can add names if we ever decide to show them somewhere :)

**Comment by sigvef** [comment]
I agree, I just added them since they were on the model anyway. Will remove.

**Comment by sigvef** [comment]
Removed.

**Pull request merged**
