### PR TITLE
Hover effects

### PR DESCRIPTION
**Pull request by leventdeniz**
Fixes issue #330 on hover effects.

- [x] Run `make lint` to ensure that all the files are formatted and using best practices.
- [x] Link to any issues this PR is solving.

(this is my first pull request, I hope I did everything right)

### CODE REVIEW

**Comment by kipkat** [comment]
That might be a good idea. I asked @lionleaf if we can use [Hover.css](http://ianlunn.github.io/Hover/) in the navigation bar and he didn't answer.

**Comment by leventdeniz** [comment]
[Hover.css](http://ianlunn.github.io/Hover/) may be too much, since we have these minimalistic underline hover-effects and @lionleaf might want to keep this style.
But the "new dweet"-button should get a proper hover-effect.

**Comment by kipkat** [comment]
We can use the css keystokes to make them look modern.

**Comment by lionleaf** [comment]
Thanks! Works like a charm

**Comment by leventdeniz** [comment]
Awesome!

**Pull request merged**
