### PR TITLE
Make first comment sticky if it's by the dweet author

### PR DESCRIPTION
**Pull request by lionleaf**
Instagram-style. Allows users to post a comment about the
dweet that will be highlighted and always visible

### CODE REVIEW

**Comment by lionleaf** [comment]
fixes #78

**Comment by sigvef** [comment]
🚢 LGTM (don't have permission to merge myself)

**Comment by iver56** [comment]
Looks like the first comment is shown twice, with the first one in bold

**Comment by lionleaf** [comment]
Yup. Only for when there is between 1 and 3 comments, but I'm on it.

**Pull request merged**
