### PR TITLE
Hashtags improvement and code block sanitization

### PR DESCRIPTION
**Pull request by dwitterer**
I've worked a bit on the regex behind the hashtags, and the way that code blocks are handled in `dweet_card`s. I changed the regex for hashtags, such that hashtags must now be preceded by either a space, or nothing at all, and must two characters or greater (i.e length >= 2). Hashtags must still begin with a letter, and can only contain letters, numbers, and underscores. However, I have also cleaned up the regex, removing a couple redundant rules\*, so stuff such as the length limitation, or the letter-start rule can be more easily changed.

The reasoning behind the length rule was to prevent accidental hashtags such as in d/2667. I doubt that one-letter hashtags such as "#g" would have been very useful or informative anyway...

\* - Redundant rule was that we had a character range: [a-zA-Z_] followed by another range [a-zA-Z0-9_] and the \* quantifier. I cleaned this up by using the [a-zA-Z0-9_] range with a negative lookbehind for digits.

Now, to change the length limit, all we would need to do is change the `{2,}` to a `*`, and to enable numerical-starting hashtags, we would just need to remove the negative lookbehind `(?<!\d)`...

I have also made it so that all links get removed from code blocks, to keep those clean, and to allow them to be used for escaping hashtags or mentions, like on discord. This, however, now means that we need to do `insert_code_blocks` AFTER `insert_magic_links`, but that's a non-issue...

Fixes (some of?) #334

### CODE REVIEW

**Comment by stianjensen** [comment]
> Ok, so now the tests are failing because of the single-character hashtag test. Is there a reason we need to test for that? We don't need single-character hashtags...

Sounds like we don't need that single-char test! But the other failing tests probably need fixing.

**Comment by dwitterer** [comment]
What other failing tests? This is the only one that fails now. I've fixed all the other ones.

**Comment by dwitterer** [comment]
After a discussion on Discord with @lionleaf, I am removing the 2-char minimum limit for hashtags. The problems that one-character hashtags have caused should be fixed anyway, and noone uses single-character hashtags anyway. So, as lionleaf seems to insist on having them, I am adding them back.

Lionleaf now needs to write some tests for the new fixes, merge this in, and then I will open a new PR for numerical hashtags, and hashtags will be good for now... :D

**Comment by dwitterer** [comment]
I've also enabled hashtags beginning with numbers, since the space precedence check makes them safe to use now. Also added an if statement to make sure that those tags need to have at least one letter - this prevents senseless tags like #78992245, and (mainly why I did this) makes it more like twitter's hashtag handling. This extra check can be removed if you don't like it, but otherwise you just need to add the new tests, test my changes out for yourself, and this PR is ready to merge :D!

**Comment by dwitterer** [comment]
Covered, and expanded upon in #424.

**Pull request closed without merging**
